name: attendance
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:


  dartx: ^1.1.0
  dartz: ^0.10.1
  dio: ^4.0.6
  
  flutter:
    sdk: flutter

  


  flutter_screenutil: ^5.9.0
  
  
  cupertino_icons: ^1.0.2
  pusher_channels_flutter: ^2.2.0
  intl: ^0.18.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_phoenix: ^1.1.1
  flutter_inappwebview: ^5.7.2+3
  flutter_smart_dialog: ^4.9.4
  flutter_bloc: ^8.1.3
  flutter_launcher_icons:
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.7
  freezed: ^2.2.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  image_picker: ^1.0.2
  json_serializable: ^6.4.1
  pretty_dio_logger: ^1.2.0-beta-1
  lottie: ^2.6.0
  retrofit: ^3.3.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  internet_connection_checker: ^1.0.0+1
  analyzer: ^5.13.0
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  country_picker: ^2.0.20

dev_dependencies:
  build_runner: ^2.1.11

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  retrofit_generator: ^4.0.1



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300


flutter_assets:
  assets_path: assets/
  output_path: lib/presentation/resources/
  filename: assets_manager.dart